import type { Post, SelfCareKey, SelfCareConfig, MoodOption } from "@/types";

export const SAMPLE_POSTS: Post[] = [
    {
        id: 1,
        text: "Today was rough. My manager completely dismissed my idea in the meeting and took credit for it later. I just needed to get this off my chest.",
        mood: "😤",
        commentsEnabled: false,
        comments: [],
        timestamp: Date.now() - 3600000 * 5,
        anonymous: true,
    },
    {
        id: 2,
        text: "Feeling weirdly grateful today. A stranger held the door and smiled at me and it genuinely made my whole afternoon better. Small things matter.",
        mood: "🙂",
        commentsEnabled: true,
        comments: [{ id: 1, text: "Love this energy 🌻", timestamp: Date.now() - 1800000 }],
        timestamp: Date.now() - 3600000 * 12,
        anonymous: false,
    },
    {
        id: 3,
        text: "I can't sleep. My brain won't stop replaying every embarrassing thing I've ever done. Why does 3am feel like a courtroom for your past self?",
        mood: "😐",
        commentsEnabled: true,
        comments: [],
        timestamp: Date.now() - 3600000 * 24,
        anonymous: true,
    },
];

export const SELF_CARE_CONFIG: Record<SelfCareKey, SelfCareConfig> = {
    water: { label: "Water", icon: "💧", goal: 8, unit: "glasses" },
    sleep: { label: "Sleep", icon: "🌙", goal: 8, unit: "hours" },
};

export const MOOD_OPTIONS: MoodOption[] = [
    { emoji: "😤", label: "Frustrated" },
    { emoji: "😢", label: "Sad" },
    { emoji: "😐", label: "Meh" },
    { emoji: "🙂", label: "Okay" },
    { emoji: "😊", label: "Good" },
    { emoji: "✨", label: "Great" },
    { emoji: "😭", label: "Crying" },
    { emoji: "😩", label: "Exhausted" },
    { emoji: "😔", label: "Down" },
    { emoji: "💔", label: "Heartbroken" },
    { emoji: "🥺", label: "Pleading" },
    { emoji: "😞", label: "Disappointed" },
    { emoji: "😡", label: "Angry" },
    { emoji: "🤬", label: "Furious" },
    { emoji: "😰", label: "Anxious" },
    { emoji: "😱", label: "Shocked" },
    { emoji: "🫠", label: "Melting" },
    { emoji: "😮‍💨", label: "Relieved" },
    { emoji: "🤯", label: "Mind blown" },
    { emoji: "😴", label: "Sleepy" },
    { emoji: "🥱", label: "Bored" },
    { emoji: "🥳", label: "Celebrating" },
    { emoji: "🤩", label: "Starstruck" },
    { emoji: "😎", label: "Cool" },
    { emoji: "🥰", label: "Loved" },
    { emoji: "🤗", label: "Hugging" },
    { emoji: "😌", label: "Peaceful" },
    { emoji: "🤷", label: "Unsure" },
    { emoji: "🤔", label: "Thinking" },
    { emoji: "😬", label: "Nervous" },
    { emoji: "🥲", label: "Bittersweet" },
    { emoji: "😏", label: "Smug" },
    { emoji: "💀", label: "Dead inside" },
    { emoji: "🙈", label: "Can't look" },
    { emoji: "🫶", label: "Grateful" },
    { emoji: "🔥", label: "On fire" },
    { emoji: "💭", label: "Overthinking" },
    { emoji: "🌊", label: "Overwhelmed" },
    { emoji: "🌸", label: "Soft" },
    { emoji: "🌈", label: "Hopeful" },
];
