import type { Post, Whisper, WhisperMemory, SelfCareKey, SelfCareConfig, MoodOption } from "@/types";

export const MAX_UNSIGNED_POSTS_PER_DAY = 3;
export const WHISPER_DURATION_MS = 48 * 60 * 60 * 1000;
export const POSTS_PER_PAGE = 5;
export const MOCK_CURRENT_USER_ID = "user_current";

export const SAMPLE_POSTS: Post[] = [
    {
        id: 1,
        text: "Today was rough. My manager completely dismissed my idea in the meeting and took credit for it later. I just needed to get this off my chest.",
        mood: "😤",
        commentsEnabled: false,
        hideIdentity: true,
        authorId: null,
        authorDisplayId: null,
        comments: [],
        reactions: { hugs: 12, meToo: 5 },
        timestamp: Date.now() - 3600000 * 2,
    },
    {
        id: 2,
        text: "Feeling weirdly grateful today. A stranger held the door and smiled at me and it genuinely made my whole afternoon better. Small things matter.",
        mood: "🙂",
        commentsEnabled: true,
        hideIdentity: false,
        authorId: "user_abc123",
        authorDisplayId: "7382",
        comments: [
            {
                id: 1,
                text: "Love this energy 🌻",
                timestamp: Date.now() - 1800000,
                authorId: "user_def456",
                authorDisplayId: "4519",
                hideIdentity: false,
            },
        ],
        reactions: { hugs: 24, meToo: 8 },
        timestamp: Date.now() - 3600000 * 5,
    },
    {
        id: 3,
        text: "I can't sleep. My brain won't stop replaying every embarrassing thing I've ever done. Why does 3am feel like a courtroom for your past self?",
        mood: "😐",
        commentsEnabled: true,
        hideIdentity: true,
        authorId: "user_ghi789",
        authorDisplayId: "2091",
        comments: [],
        reactions: { hugs: 7, meToo: 15 },
        timestamp: Date.now() - 3600000 * 12,
    },
    {
        id: 4,
        text: "Anyone else feel like they're just performing being okay? Like, I smile at work all day and then come home and just... collapse.",
        mood: "🫠",
        commentsEnabled: true,
        hideIdentity: true,
        authorId: "user_jkl012",
        authorDisplayId: "5643",
        comments: [
            {
                id: 2,
                text: "This hits too close to home. You're not alone.",
                timestamp: Date.now() - 3600000 * 10,
                authorId: "user_abc123",
                authorDisplayId: "7382",
                hideIdentity: false,
            },
        ],
        reactions: { hugs: 41, meToo: 29 },
        timestamp: Date.now() - 3600000 * 18,
    },
    {
        id: 5,
        text: "My therapist told me it's okay to outgrow people. That doesn't make it hurt less, but it makes it make sense.",
        mood: "🥲",
        commentsEnabled: true,
        hideIdentity: false,
        authorId: "user_mno345",
        authorDisplayId: "9127",
        comments: [],
        reactions: { hugs: 33, meToo: 12 },
        timestamp: Date.now() - 3600000 * 24,
    },
    {
        id: 6,
        text: "Took a walk today instead of doomscrolling. 10/10 would recommend. The sky was doing something crazy with the clouds.",
        mood: "😊",
        commentsEnabled: true,
        hideIdentity: false,
        authorId: MOCK_CURRENT_USER_ID,
        authorDisplayId: "7382",
        comments: [
            {
                id: 3,
                text: "Proud of you for that!",
                timestamp: Date.now() - 3600000 * 20,
                authorId: "user_def456",
                authorDisplayId: "4519",
                hideIdentity: false,
            },
        ],
        reactions: { hugs: 18, meToo: 4 },
        timestamp: Date.now() - 3600000 * 30,
    },
    {
        id: 7,
        text: "I got rejected from my dream job today. Three rounds of interviews for nothing. I don't even know what I did wrong.",
        mood: "😢",
        commentsEnabled: true,
        hideIdentity: true,
        authorId: null,
        authorDisplayId: null,
        comments: [],
        reactions: { hugs: 56, meToo: 19 },
        timestamp: Date.now() - 3600000 * 36,
    },
    {
        id: 8,
        text: "Does anyone else's cat just... stare at them like they know all your secrets? Because mine definitely does.",
        mood: "🙈",
        commentsEnabled: true,
        hideIdentity: false,
        authorId: MOCK_CURRENT_USER_ID,
        authorDisplayId: "7382",
        comments: [
            {
                id: 4,
                text: "Mine judges me every time I eat cereal for dinner 😂",
                timestamp: Date.now() - 3600000 * 33,
                authorId: "user_jkl012",
                authorDisplayId: "5643",
                hideIdentity: false,
            },
            {
                id: 5,
                text: "They absolutely do and I'm here for it",
                timestamp: Date.now() - 3600000 * 32,
                authorId: "user_mno345",
                authorDisplayId: "9127",
                hideIdentity: false,
            },
        ],
        reactions: { hugs: 9, meToo: 22 },
        timestamp: Date.now() - 3600000 * 42,
    },
    {
        id: 9,
        text: "Haven't talked to my best friend in 3 months. We didn't fight or anything. Life just... happened. And now it feels too late to reach out.",
        mood: "😔",
        commentsEnabled: true,
        hideIdentity: true,
        authorId: "user_pqr678",
        authorDisplayId: "3318",
        comments: [],
        reactions: { hugs: 28, meToo: 37 },
        timestamp: Date.now() - 3600000 * 48,
    },
    {
        id: 10,
        text: "Cooked a real meal today instead of ordering in. It wasn't great but I made it with my own hands and that counts for something.",
        mood: "🫶",
        commentsEnabled: true,
        hideIdentity: false,
        authorId: "user_stu901",
        authorDisplayId: "6204",
        comments: [],
        reactions: { hugs: 15, meToo: 6 },
        timestamp: Date.now() - 3600000 * 60,
    },
];

export const SELF_CARE_CONFIG: Record<SelfCareKey, SelfCareConfig> = {
    water: { label: "Water", icon: "💧", goal: 8, unit: "glasses" },
    sleep: { label: "Sleep", icon: "🌙", goal: 8, unit: "hours" },
};

export const MOOD_OPTIONS: MoodOption[] = [
    { emoji: "😤", label: "Frustrated" },
    { emoji: "😢", label: "Sad" },
    { emoji: "😐", label: "Meh" },
    { emoji: "🙂", label: "Okay" },
    { emoji: "😊", label: "Good" },
    { emoji: "✨", label: "Great" },
    { emoji: "😭", label: "Crying" },
    { emoji: "😩", label: "Exhausted" },
    { emoji: "😔", label: "Down" },
    { emoji: "💔", label: "Heartbroken" },
    { emoji: "🥺", label: "Pleading" },
    { emoji: "😞", label: "Disappointed" },
    { emoji: "😡", label: "Angry" },
    { emoji: "🤬", label: "Furious" },
    { emoji: "😰", label: "Anxious" },
    { emoji: "😱", label: "Shocked" },
    { emoji: "🫠", label: "Melting" },
    { emoji: "😮‍💨", label: "Relieved" },
    { emoji: "🤯", label: "Mind blown" },
    { emoji: "😴", label: "Sleepy" },
    { emoji: "🥱", label: "Bored" },
    { emoji: "🥳", label: "Celebrating" },
    { emoji: "🤩", label: "Starstruck" },
    { emoji: "😎", label: "Cool" },
    { emoji: "🥰", label: "Loved" },
    { emoji: "🤗", label: "Hugging" },
    { emoji: "😌", label: "Peaceful" },
    { emoji: "🤷", label: "Unsure" },
    { emoji: "🤔", label: "Thinking" },
    { emoji: "😬", label: "Nervous" },
    { emoji: "🥲", label: "Bittersweet" },
    { emoji: "😏", label: "Smug" },
    { emoji: "💀", label: "Dead inside" },
    { emoji: "🙈", label: "Can't look" },
    { emoji: "🫶", label: "Grateful" },
    { emoji: "🔥", label: "On fire" },
    { emoji: "💭", label: "Overthinking" },
    { emoji: "🌊", label: "Overwhelmed" },
    { emoji: "🌸", label: "Soft" },
    { emoji: "🌈", label: "Hopeful" },
];

export const SAMPLE_WHISPERS: Whisper[] = [
    {
        id: 1,
        participantOneId: MOCK_CURRENT_USER_ID,
        participantTwoId: "user_abc123",
        participantOneDisplayId: "7382",
        participantTwoDisplayId: "4519",
        status: "active",
        expiresAt: Date.now() + 36 * 60 * 60 * 1000,
        extended: false,
        requestedById: "user_abc123",
        messages: [
            { id: 1, senderId: "user_abc123", senderDisplayId: "4519", text: "Hey, I saw your comment about the late night thoughts. I totally get it.", timestamp: Date.now() - 3600000 * 2 },
            { id: 2, senderId: MOCK_CURRENT_USER_ID, senderDisplayId: "7382", text: "Right? It's like 3am is when your brain decides to replay every cringy moment.", timestamp: Date.now() - 3600000 },
            { id: 3, senderId: "user_abc123", senderDisplayId: "4519", text: "Exactly. I've started keeping a notebook by my bed. Sometimes writing it down helps.", timestamp: Date.now() - 1800000 },
        ],
        createdAt: Date.now() - 3600000 * 24,
    },
];

export const SAMPLE_WHISPER_REQUESTS: Whisper[] = [
    {
        id: 2,
        participantOneId: "user_def456",
        participantTwoId: MOCK_CURRENT_USER_ID,
        participantOneDisplayId: "2091",
        participantTwoDisplayId: "7382",
        status: "pending",
        expiresAt: 0,
        extended: false,
        requestedById: "user_def456",
        messages: [],
        createdAt: Date.now() - 3600000,
    },
];

export const SAMPLE_WHISPER_MEMORIES: WhisperMemory[] = [
    {
        id: 1,
        whisperId: 3,
        whisper: {
            id: 3,
            participantOneId: MOCK_CURRENT_USER_ID,
            participantTwoId: "user_ghi789",
            participantOneDisplayId: "7382",
            participantTwoDisplayId: "8901",
            status: "expired",
            expiresAt: Date.now() - 3600000 * 48,
            extended: true,
            requestedById: MOCK_CURRENT_USER_ID,
            messages: [
                { id: 1, senderId: "user_ghi789", senderDisplayId: "8901", text: "Thanks for reaching out. It helped talking to someone.", timestamp: Date.now() - 3600000 * 96 },
                { id: 2, senderId: MOCK_CURRENT_USER_ID, senderDisplayId: "7382", text: "Same here. Take care of yourself.", timestamp: Date.now() - 3600000 * 95 },
            ],
            createdAt: Date.now() - 3600000 * 120,
        },
        savedAt: Date.now() - 3600000 * 48,
    },
];
